apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.label }}-deploy
  labels:
    app: {{ .Values.label }}
spec:
  replicas: {{.Values.app.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.label }}
    spec:
      containers:
        - name: {{ .Values.label }}-app
          image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
          ports:
          - containerPort: {{ .Values.app.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secret